import {
  CharacterConfig,
  CharacterType,
  VehicleConfig,
  VehicleType,
  Building,
  RoadSegment,
  TrafficLight,
  TrafficSign,
  ZebraCrossing,
  Pedestrian3D,
  NPCVehicle3D,
  RailwayCrossing,
  Mission,
} from './types';

export const CITY_SIZE = {
  width: 500,
  depth: 500,
};

// 1. Karakter Pengendara (Laki-laki / Perempuan)
export const CHARACTERS: Record<CharacterType, CharacterConfig> = {
  laki_laki: {
    id: 'laki_laki',
    name: 'Budi Hartono',
    avatar: '👦',
    title: 'Pelajar Kelas 4 SD',
    description: 'Siswa ceria dan cermat yang selalu menaati tata tertib berlalu lintas di jalan raya.',
    jacketColor: '#16a34a', // Emerald green jacket
    helmetColor: '#22c55e', // Bright green helmet
    badge: '🎖️ Pramuka Penggalang',
  },
  perempuan: {
    id: 'perempuan',
    name: 'Siti Rahma',
    avatar: '👧',
    title: 'Pelajar Teladan Kelas 4 SD',
    description: 'Siswi disiplin dan teliti yang hapal peta kota serta patuh pada rambu dan marka trotoar.',
    jacketColor: '#0d9488', // Teal green jacket
    helmetColor: '#14b8a6', // Teal helmet with pink stripe
    badge: '⭐ Duta Keselamatan Cilik',
  },
};

// 2. Pilihan Kendaraan (Motor, Mobil, Sepeda)
export const VEHICLES: Record<VehicleType, VehicleConfig> = {
  motor: {
    id: 'motor',
    name: 'Sepeda Motor Skuter Klasik',
    tagline: 'Lincah, Gesit & Klasik',
    maxSpeed: 12.5, // ~40 km/h
    acceleration: 8.5,
    brakeDecel: 16.0,
    turnSpeed: 1.6,
    icon: '🛵',
    color: '#38bdf8', // Light blue classic retro
    description: 'Skuter klasik retro biru muda dengan handling stabil dan klakson nyaring.',
    width: 0.8,
    length: 1.8,
  },
  mobil: {
    id: 'mobil',
    name: 'Mobil Kompak Kota',
    tagline: 'Aman, Nyaman & Luas',
    maxSpeed: 15.0, // ~48 km/h (lebih cepat)
    acceleration: 7.2,
    brakeDecel: 18.0,
    turnSpeed: 1.25, // radius putar lebih lebar
    icon: '🚗',
    color: '#ea580c', // Orange sporty
    description: 'Mobil empat roda yang aman dan stabil. Memerlukan ancang-ancang saat berbelok di persimpangan.',
    width: 1.8,
    length: 3.6,
  },
  sepeda: {
    id: 'sepeda',
    name: 'Sepeda Onthel Ceria',
    tagline: 'Ramah Lingkungan & Sangat Lincah',
    maxSpeed: 7.5, // ~24 km/h (santai)
    acceleration: 6.0,
    brakeDecel: 14.0,
    turnSpeed: 2.1, // radius putar sangat lincah
    icon: '🚲',
    color: '#0284c7', // Biru laut
    description: 'Sepeda kayuh santai dengan bel kring-kring. Sangat mudah meliuk di gang dan trotoar.',
    width: 0.6,
    length: 1.5,
  },
};

// 3. Jaringan Jalan Raya Indonesia
export const ROADS_3D: RoadSegment[] = [
  // Arah Horizontal (Timur - Barat)
  {
    id: 'road-pendidikan',
    x: 0,
    z: -120,
    width: 440,
    depth: 18,
    name: 'Jl. Pendidikan (Zona SDN Gajahrejo 1)',
    direction: 'h',
  },
  {
    id: 'road-garuda',
    x: 0,
    z: 0,
    width: 440,
    depth: 22,
    name: 'Jl. Garuda Raya (Boulevard Utama)',
    direction: 'h',
  },
  {
    id: 'road-melati',
    x: 0,
    z: 120,
    width: 440,
    depth: 18,
    name: 'Jl. Melati Sejahtera (Pemukiman Warga)',
    direction: 'h',
  },

  // Arah Vertikal (Utara - Selatan)
  {
    id: 'road-merdeka',
    x: -140,
    z: 0,
    width: 18,
    depth: 300,
    name: 'Jl. Merdeka Barat (Kawasan Balai Kota)',
    direction: 'v',
  },
  {
    id: 'road-pahlawan',
    x: -20,
    z: 0,
    width: 20,
    depth: 300,
    name: 'Jl. Pahlawan (Perpustakaan & Sekolah)',
    direction: 'v',
  },
  {
    id: 'road-kartini',
    x: 100,
    z: 0,
    width: 18,
    depth: 300,
    name: 'Jl. Kartini Timur (Kawasan Puskesmas & Pasar)',
    direction: 'v',
  },
  {
    id: 'road-diponegoro',
    x: 180,
    z: 0,
    width: 18,
    depth: 300,
    name: 'Jl. Diponegoro (Kawasan Taman Kota)',
    direction: 'v',
  },
];

// Perlintasan Kereta Api Indonesia (Rel memotong kota di z = 60)
export const RAILWAY_CROSSING_DATA: RailwayCrossing = {
  id: 'rail-pahlawan',
  x: -20,
  z: 60,
  isClosed: false,
  barrierAngle: 0, // 0 = tegak (buka), Math.PI / 2 = horizontal (tutup)
  trainActive: false,
  trainX: -260,
  timer: 14,
};

// Penyeberangan Pejalan Kaki (Zebra Cross)
export const ZEBRAS_3D: ZebraCrossing[] = [
  {
    id: 'zebra-school',
    x: -20,
    z: -95,
    width: 18,
    depth: 6,
    orientation: 'h',
    name: 'Zebra Cross SDN Gajahrejo 1',
  },
  {
    id: 'zebra-garuda-mid',
    x: -45,
    z: 0,
    width: 6,
    depth: 20,
    orientation: 'v',
    name: 'Zebra Cross Perempatan Garuda',
  },
  {
    id: 'zebra-puskesmas',
    x: 100,
    z: -95,
    width: 18,
    depth: 6,
    orientation: 'h',
    name: 'Zebra Cross Puskesmas Sehat',
  },
  {
    id: 'zebra-pasar',
    x: 100,
    z: 95,
    width: 18,
    depth: 6,
    orientation: 'h',
    name: 'Zebra Cross Pasar Tradisional',
  },
];

// Gedung & Landmark Kota Indonesia
export const BUILDINGS_3D: Building[] = [
  // Sektor Utara
  {
    id: 'balai-desa',
    x: -140,
    z: -160,
    width: 38,
    depth: 30,
    height: 16,
    type: 'townhall',
    name: 'Kantor Balai Kota Suka Maju',
    subname: 'Pusat Pemerintahan & Layanan Publik',
    color: '#854d0e',
    roofColor: '#78350f',
    badgeIcon: '🏛️',
  },
  {
    id: 'sdn-gajahrejo',
    x: -20,
    z: -165,
    width: 58,
    depth: 36,
    height: 16,
    type: 'school',
    name: 'SDN Gajahrejo 1',
    subname: 'Sekolah Dasar Ramah Anak',
    color: '#b91c1c',
    roofColor: '#991b1b',
    badgeIcon: '🏫',
  },
  {
    id: 'puskesmas',
    x: 100,
    z: -160,
    width: 44,
    depth: 32,
    height: 15,
    type: 'clinic',
    name: 'Puskesmas Sehat Bersama',
    subname: 'Pelayanan Kesehatan 24 Jam',
    color: '#15803d',
    roofColor: '#166534',
    badgeIcon: '🏥',
  },

  // Sektor Tengah
  {
    id: 'masjid',
    x: -140,
    z: -60,
    width: 32,
    depth: 32,
    height: 19,
    type: 'mosque',
    name: 'Masjid Al-Ikhlas',
    subname: 'Pusat Ibadah & Kerukunan',
    color: '#0d9488',
    roofColor: '#115e59',
    badgeIcon: '🕌',
  },
  {
    id: 'perpustakaan-nasional',
    x: -60,
    z: -60,
    width: 42,
    depth: 30,
    height: 17,
    type: 'library',
    name: 'Perpustakaan Nasional Cerdas',
    subname: 'Gudang Ensiklopedia & Buku Pelajar',
    color: '#2563eb',
    roofColor: '#1d4ed8',
    badgeIcon: '📚',
  },
  {
    id: 'pos-polisi',
    x: -42,
    z: 16,
    width: 12,
    depth: 12,
    height: 8,
    type: 'police',
    name: 'Pos Polisi Sahabat Anak',
    subname: 'Pengayom & Penjaga Ketertiban',
    color: '#1e3a8a',
    roofColor: '#1e40af',
    badgeIcon: '👮',
  },
  {
    id: 'supermarket',
    x: 40,
    z: -60,
    width: 48,
    depth: 28,
    height: 16,
    type: 'supermarket',
    name: 'Supermarket Nusantara Indah',
    subname: 'Pusat Perbelanjaan & Kebutuhan',
    color: '#d97706',
    roofColor: '#b45309',
    badgeIcon: '🛒',
  },
  {
    id: 'taman-kota',
    x: 180,
    z: -60,
    width: 52,
    depth: 52,
    height: 5,
    type: 'park',
    name: 'Taman Kota Ramah Anak',
    subname: 'Fasilitas Bermain, Pohon & Air Mancur',
    color: '#16a34a',
    roofColor: '#15803d',
    badgeIcon: '🌳',
  },

  // Sektor Selatan
  {
    id: 'rumah-budi',
    x: -140,
    z: 155,
    width: 28,
    depth: 24,
    height: 12,
    type: 'house',
    name: 'Rumah Pengendara (Titik Awal)',
    subname: 'Jl. Melati No. 12',
    color: '#ea580c',
    roofColor: '#c2410c',
    badgeIcon: '🏡',
  },
  {
    id: 'stasiun-ka',
    x: -80,
    z: 60,
    width: 38,
    depth: 22,
    height: 13,
    type: 'station',
    name: 'Stasiun Kereta Api Kota',
    subname: 'Perlintasan Jalur Rel Kereta',
    color: '#0284c7',
    roofColor: '#0369a1',
    badgeIcon: '🚆',
  },
  {
    id: 'toko-koperasi',
    x: 35,
    z: 155,
    width: 32,
    depth: 24,
    height: 13,
    type: 'shop',
    name: 'Toko Buku & Alat Tulis Ceria',
    subname: 'Perlengkapan Sekolah Pelajar',
    color: '#4f46e5',
    roofColor: '#4338ca',
    badgeIcon: '✏️',
  },
  {
    id: 'pasar-tradisional',
    x: 100,
    z: 160,
    width: 52,
    depth: 40,
    height: 14,
    type: 'market',
    name: 'Pasar Tradisional Beringin',
    subname: 'Pusat Sayur, Buah & Jajanan',
    color: '#c2410c',
    roofColor: '#9a3412',
    badgeIcon: '🍉',
  },
];

// Lampu Pengatur Lalu Lintas (APILL)
export const TRAFFIC_LIGHTS_3D: TrafficLight[] = [
  {
    id: 'tl-pahlawan-north',
    x: -12,
    z: 22,
    roadDirection: 'v',
    facing: 'up',
    state: 'red',
    timer: 8,
    redDuration: 8,
    yellowDuration: 2,
    greenDuration: 8,
    stopLineZ: 14,
  },
  {
    id: 'tl-garuda-east',
    x: -36,
    z: -12,
    roadDirection: 'h',
    facing: 'right',
    state: 'green',
    timer: 8,
    redDuration: 8,
    yellowDuration: 2,
    greenDuration: 8,
    stopLineX: -32,
  },
  {
    id: 'tl-school',
    x: -10,
    z: -82,
    roadDirection: 'v',
    facing: 'up',
    state: 'green',
    timer: 7,
    redDuration: 6,
    yellowDuration: 2,
    greenDuration: 7,
    stopLineZ: -88,
  },
];

// Rambu-Rambu Edukasi HD & Plang Penunjuk Arah
export const TRAFFIC_SIGNS_3D: TrafficSign[] = [
  {
    id: 'sign-stop-merdeka',
    x: -130,
    z: 12,
    type: 'stop',
    title: 'Rambu STOP (Wajib Berhenti)',
    description: 'Wajib berhenti penuh dan memastikan arus lalu lintas persimpangan aman.',
    meaning: 'Berhenti sebelum garis marka melintang.',
    radius: 9,
    quiz: {
      question: 'Ketika kamu melihat Rambu STOP segi delapan merah di persimpangan jalan, tindakan apakah yang paling tepat?',
      options: [
        'A. Memperlambat sedikit lalu langsung tancap gas menyeberang',
        'B. Berhenti penuh sebelum garis marka, tengok kanan-kiri, baru melaju jika aman',
        'C. Membunyikan klakson panjang dan tetap melaju cepat',
        'D. Berputar arah kembali ke titik awal',
      ],
      correctIndex: 1,
      explanation: 'Tepat sekali! Rambu STOP adalah rambu larangan yang mewajibkan semua pengendara berhenti secara sempurna sebelum garis berhenti, lalu memastikan persimpangan aman sebelum melanjutkan perjalanan.',
      curriculumConcept: 'Rambu Larangan & Marka Garis Berhenti',
    },
  },
  {
    id: 'sign-traffic-light',
    x: -28,
    z: 16,
    type: 'traffic_light',
    title: 'Rambu Lampu APILL',
    description: 'Peringatan persimpangan berlampu pengatur lalu lintas.',
    meaning: 'Perhatikan sinyal: Merah berhenti, Hijau jalan.',
    radius: 9,
    quiz: {
      question: 'Apa arti dan tindakan yang benar saat lampu kuning menyala pada Alat Pemberi Isyarat Lalu Lintas (APILL)?',
      options: [
        'A. Melaju secepat-cepatnya sebelum berubah menjadi lampu merah',
        'B. Mengurangi kecepatan dan bersiap untuk berhenti dengan aman sebelum garis marka',
        'C. Menutup mata dan terus melajukan kendaraan',
        'D. Mematikan mesin kendaraan seketika di tengah jalan',
      ],
      correctIndex: 1,
      explanation: 'Hebat! Lampu kuning adalah sinyal peringatan bahwa lampu merah akan segera menyala. Pengendara harus berhati-hati memperlambat laju dan bersiap berhenti dengan aman.',
      curriculumConcept: 'Rambu Peringatan & Sinyal Lampu APILL',
    },
  },
  {
    id: 'sign-railway-pahlawan',
    x: -12,
    z: 48,
    type: 'railway',
    title: 'Rambu Perlintasan Kereta Api',
    description: 'Peringatan perlintasan rel kereta api dengan palang pintu otomatis.',
    meaning: 'Wajib berhenti saat palang pintu mulai menutup dan sirine berbunyi.',
    radius: 10,
    quiz: {
      question: 'Jika sirine perlintasan kereta api berbunyi dan palang pintu mulai turun, sikap tertib apa yang wajib kamu lakukan?',
      options: [
        'A. Berhenti di belakang palang pintu dan sabar menunggu hingga kereta selesai lewat',
        'B. Menerobos dengan cepat dari sela-sela palang sebelum kereta mendekat',
        'C. Membunyikan klakson agar masinis kereta berhenti',
        'D. Naik ke atas rel kereta api untuk merekam video',
      ],
      correctIndex: 0,
      explanation: 'Luar biasa! Jangan pernah menerobos palang perlintasan sebidang rel kereta api. Selalu dahulukan perjalanan kereta api demi keselamatan nyawa.',
      curriculumConcept: 'Keselamatan Perlintasan Sebidang Kereta Api',
    },
  },
  {
    id: 'sign-zoss',
    x: -10,
    z: -78,
    type: 'school_zone',
    title: 'Rambu Zona Selamat Sekolah (ZOSS)',
    description: 'Kawasan sekolah banyak siswa melintas. Batas kecepatan maksimal 20 km/jam.',
    meaning: 'Kurangi kecepatan & dahulukan anak sekolah.',
    radius: 9,
    quiz: {
      question: 'Mengapa di depan kawasan sekolah dipasang rambu Zona Selamat Sekolah (ZOSS) dan marka aspal merah?',
      options: [
        'A. Sebagai area balapan khusus setelah jam pulang sekolah',
        'B. Mengingatkan pengendara untuk memperlambat laju (maks. 20 km/jam) karena banyak siswa menyeberang',
        'C. Tempat parkir bebas untuk semua kendaraan warga',
        'D. Sekadar hiasan warna-warni jalan raya',
      ],
      correctIndex: 1,
      explanation: 'Benar sekali! Rambu ZOSS melindungi adik-adik dan teman-teman sekolah yang menyeberang jalan. Pengendara harus berkendara sangat perlahan maksimal 20 km/jam.',
      curriculumConcept: 'Zona Selamat Sekolah (ZOSS) & Hak Pejalan Kaki Cilik',
    },
  },
  {
    id: 'sign-zebra-sd',
    x: -10,
    z: -102,
    type: 'zebra',
    title: 'Rambu Penyeberangan Zebra Cross',
    description: 'Jalur penyeberangan aman untuk pejalan kaki.',
    meaning: 'Dahulukan pejalan kaki yang melintas.',
    radius: 9,
    quiz: {
      question: 'Siapakah yang memiliki hak prioritas utama di jalan raya saat berada di atas marka Zebra Cross bergaris putih?',
      options: [
        'A. Pejalan kaki yang sedang menyeberang jalan dengan tertib',
        'B. Sepeda motor yang ingin melaju kencang menyalip',
        'C. Mobil angkot yang sedang mengejar setoran',
        'D. Kendaraan besar yang membunyikan klakson paling keras',
      ],
      correctIndex: 0,
      explanation: 'Tepat! Pejalan kaki adalah pengguna jalan yang paling rentan. Semua kendaraan wajib memberi jalan dan berhenti penuh saat ada orang menyeberang di Zebra Cross.',
      curriculumConcept: 'Rambu Perintah & Hak Pejalan Kaki di Zebra Cross',
    },
  },
  {
    id: 'sign-no-right-turn',
    x: 90,
    z: 14,
    type: 'no_right_turn',
    title: 'Rambu Dilarang Belok Kanan',
    description: 'Dilarang membelokkan kendaraan ke arah kanan di persimpangan ini.',
    meaning: 'Lurus atau belok ke kiri saja.',
    radius: 9,
    quiz: {
      question: 'Apa arti rambu lingkaran putih dengan garis tepi merah, serta gambar panah kanan yang dicoret garis merah melintang?',
      options: [
        'A. Semua kendaraan dilarang berbelok ke arah kanan di persimpangan ini',
        'B. Diwajibkan berbelok ke kanan jika jalanan sepi',
        'C. Tempat belok khusus untuk sepeda motor saja',
        'D. Menunjukkan arah kantor polisi di sebelah kanan',
      ],
      correctIndex: 0,
      explanation: 'Sempurna! Garis diagonal merah yang mencoret lambang panah menandakan larangan mutlak. Pengendara hanya diizinkan melaju lurus atau berbelok ke kiri.',
      curriculumConcept: 'Rambu Larangan Belok & Manajemen Arus Lalu Lintas',
    },
  },
  {
    id: 'sign-no-entry-pasar',
    x: 90,
    z: 110,
    type: 'no_entry',
    title: 'Rambu Dilarang Masuk (No Entry)',
    description: 'Dilarang memasuki jalur khusus pejalan kaki atau jalur satu arah.',
    meaning: 'Gunakan pintu gerbang utama pasar.',
    radius: 9,
    quiz: {
      question: 'Apa makna rambu berbentuk lingkaran merah dengan balok putih horizontal di tengahnya?',
      options: [
        'A. Tempat parkir kendaraan gratis di area pasar',
        'B. Dilarang masuk bagi semua jenis kendaraan bermotor dari arah ini',
        'C. Jalan bebas hambatan tanpa batas kecepatan',
        'D. Pos tempat mencuci kendaraan',
      ],
      correctIndex: 1,
      explanation: 'Pintar! Rambu lingkaran merah dengan balok putih adalah Rambu Dilarang Masuk. Jalur tersebut biasanya merupakan jalan satu arah atau jalur khusus pejalan kaki.',
      curriculumConcept: 'Rambu Larangan Masuk Jalur Satu Arah',
    },
  },
];

// Kendaraan NPC Dinamis Lalu-lalang
export const INITIAL_NPC_VEHICLES: NPCVehicle3D[] = [
  {
    id: 'npc-car-red',
    type: 'car',
    color: '#dc2626', // Sedan merah
    x: -80,
    z: -3,
    speed: 6.5,
    direction: 'east',
    minCoord: -200,
    maxCoord: 200,
  },
  {
    id: 'npc-angkot-blue',
    type: 'angkot',
    color: '#0284c7', // Angkot biru khas
    x: 104,
    z: -60,
    speed: 5.5,
    direction: 'south',
    minCoord: -140,
    maxCoord: 140,
  },
  {
    id: 'npc-motor-warga',
    type: 'motor',
    color: '#eab308', // Motor bebek kuning
    x: -16,
    z: 80,
    speed: 7.2,
    direction: 'north',
    minCoord: -140,
    maxCoord: 140,
  },
  {
    id: 'npc-box-truck',
    type: 'truck',
    color: '#f97316', // Mobil boks logistik
    x: 40,
    z: 124,
    speed: 5.0,
    direction: 'west',
    minCoord: -200,
    maxCoord: 200,
  },
  {
    id: 'npc-car-green',
    type: 'car',
    color: '#16a34a', // City car hijau
    x: -50,
    z: -123,
    speed: 6.0,
    direction: 'east',
    minCoord: -200,
    maxCoord: 200,
  },
];

// Pejalan Kaki 3D
export const PEDESTRIANS_3D: Pedestrian3D[] = [
  {
    id: 'ped-1',
    x: -30,
    z: -95,
    startX: -30,
    startZ: -95,
    targetX: -10,
    targetZ: -95,
    speed: 0.08,
    direction: 1,
    name: 'Siswa Merah Putih',
    color: '#ef4444',
  },
  {
    id: 'ped-2',
    x: 90,
    z: -95,
    startX: 90,
    startZ: -95,
    targetX: 110,
    targetZ: -95,
    speed: 0.07,
    direction: 1,
    name: 'Budi Kecil',
    color: '#0284c7',
  },
  {
    id: 'ped-3',
    x: -45,
    z: -8,
    startX: -45,
    startZ: -8,
    targetX: -45,
    targetZ: 8,
    speed: 0.06,
    direction: 1,
    name: 'Ibu Guru Ani',
    color: '#16a34a',
  },
];

// 4. Misi Dinamis yang Bervariasi (Sesuai Permintaan User)
export const MISSIONS_3D: Mission[] = [
  {
    id: 1,
    title: 'Misi 1: Rumah ke Perpustakaan Nasional',
    locationFrom: 'Rumah Pengendara (Titik A)',
    locationTo: 'Perpustakaan Nasional Cerdas (Titik B)',
    storyDescription:
      'Tugas meminjam ensiklopedia ilmu pengetahuan! Kendarai kendaraanmu dari Rumah menuju Perpustakaan Nasional. Ingat hafalan petamu: menyusuri Jl. Melati, belok utara ke Jl. Pahlawan, dan amati rambu lalu lintas sebelum tiba!',
    curriculumTopic: 'Membaca Denah Perkotaan & Kepatuhan Arah',
    startPoint: { x: -140, z: 120, angle: 0 },
    targetPoint: { x: -60, z: -40, radius: 14, label: 'Gerbang Perpustakaan Nasional' },
    targetTimeSeconds: 85,
    routeRoadNames: ['Jl. Melati Sejahtera', 'Jl. Pahlawan', 'Jl. Garuda Raya'],
    checkpoints: [
      {
        id: 'm1-cp1',
        x: -70,
        z: 120,
        radius: 14,
        streetName: 'Jl. Melati Sejahtera',
        instructionText: 'Lurus ke timur di Jl. Melati Sejahtera melewati Rumah Warga.',
        subHint: 'Perhatikan pertigaan Jl. Pahlawan di depan.',
        completed: false,
        requiredRule: 'straight',
      },
      {
        id: 'm1-cp2',
        x: -20,
        z: 120,
        radius: 14,
        streetName: 'Pertigaan Jl. Pahlawan',
        instructionText: 'Di pertigaan Toko Buku, belok kiri (utara) menuju Jl. Pahlawan.',
        subHint: 'Belok ke arah kiri menuju jalur utara.',
        completed: false,
        requiredRule: 'turn_left',
      },
      {
        id: 'm1-cp3',
        x: -20,
        z: 50,
        radius: 14,
        streetName: 'Jl. Pahlawan (Dekat Rel KA)',
        instructionText: 'Lurus ke utara waspada perlintasan rel kereta api di Jl. Pahlawan!',
        subHint: 'Pastikan palang pintu kereta terbuka sebelum melintas.',
        completed: false,
        requiredRule: 'straight',
      },
      {
        id: 'm1-cp4',
        x: -20,
        z: 0,
        radius: 14,
        streetName: 'Perempatan Jl. Garuda',
        instructionText: 'Di perempatan besar berlampu lalu lintas, belok kiri ke barat menuju Perpustakaan.',
        subHint: 'Tunggu lampu hijau sebelum berbelok ke kiri.',
        completed: false,
        requiredRule: 'turn_left',
      },
      {
        id: 'm1-cp5',
        x: -55,
        z: -25,
        radius: 14,
        streetName: 'Pelataran Perpustakaan',
        instructionText: 'Belok kanan memasuki gerbang halaman Perpustakaan Nasional Cerdas.',
        subHint: 'Sentuh zona target kuning untuk menyelesaikan misi.',
        completed: false,
      },
    ],
  },
  {
    id: 2,
    title: 'Misi 2: Rumah ke Pasar Tradisional',
    locationFrom: 'Rumah Pengendara (Titik A)',
    locationTo: 'Pasar Tradisional Beringin (Titik B)',
    storyDescription:
      'Membantu belanja sayur dan buah segar! Dari Rumah menuju Pasar Tradisional. Waspada jalur perlintasan rel kereta api dan rambu Dilarang Masuk di lorong pasar.',
    curriculumTopic: 'Memahami Rambu Kereta Api & Rambu Larangan',
    startPoint: { x: -140, z: 120, angle: 0 },
    targetPoint: { x: 100, z: 140, radius: 14, label: 'Pintu Masuk Pasar Tradisional' },
    targetTimeSeconds: 80,
    routeRoadNames: ['Jl. Melati Sejahtera', 'Jl. Kartini Timur'],
    checkpoints: [
      {
        id: 'm2-cp1',
        x: -70,
        z: 120,
        radius: 14,
        streetName: 'Jl. Melati Sejahtera',
        instructionText: 'Melaju lurus ke arah timur menyusuri Jl. Melati Sejahtera.',
        subHint: 'Pertahankan laju stabil di jalur kiri.',
        completed: false,
      },
      {
        id: 'm2-cp2',
        x: -20,
        z: 120,
        radius: 14,
        streetName: 'Jl. Melati Tengah',
        instructionText: 'Lurus terus melewati perempatan Jl. Pahlawan ke arah timur.',
        subHint: 'Hati-hati kendaraan NPC yang melintas.',
        completed: false,
        requiredRule: 'straight',
      },
      {
        id: 'm2-cp3',
        x: 60,
        z: 120,
        radius: 14,
        streetName: 'Jl. Melati Timur',
        instructionText: 'Dekati persimpangan Pasar Tradisional di Jl. Kartini.',
        subHint: 'Perhatikan rambu penyeberangan jalan di depan.',
        completed: false,
      },
      {
        id: 'm2-cp4',
        x: 95,
        z: 120,
        radius: 14,
        streetName: 'Gerbang Pasar',
        instructionText: 'Amati rambu Dilarang Masuk pada lorong sempit! Masuklah lewat gerbang utama Pasar.',
        subHint: 'Belok ke area parkir pasar tradisional.',
        completed: false,
      },
    ],
  },
  {
    id: 3,
    title: 'Misi 3: Sekolah ke Taman Kota',
    locationFrom: 'SDN Gajahrejo 1 (Titik A)',
    locationTo: 'Taman Kota Ramah Anak (Titik B)',
    storyDescription:
      'Selesai jam belajar di sekolah, saatnya berangkat latihan kepramukaan siaga di Taman Kota Ramah Anak! Lewati Jl. Pendidikan dan Jl. Diponegoro dengan tertib.',
    curriculumTopic: 'Zona Selamat Sekolah (ZOSS) & Jalur Rindang',
    startPoint: { x: -20, z: -115, angle: Math.PI / 2 },
    targetPoint: { x: 180, z: -45, radius: 14, label: 'Pelataran Air Mancur Taman Kota' },
    targetTimeSeconds: 90,
    routeRoadNames: ['Jl. Pendidikan', 'Jl. Diponegoro'],
    checkpoints: [
      {
        id: 'm3-cp1',
        x: -20,
        z: -120,
        radius: 14,
        streetName: 'Jl. Pendidikan (ZOSS)',
        instructionText: 'Keluar dari gerbang SDN Gajahrejo 1, belok kiri (timur) ke Jl. Pendidikan.',
        subHint: 'Kurangi kecepatan di Zona Selamat Sekolah.',
        completed: false,
        requiredRule: 'turn_left',
      },
      {
        id: 'm3-cp2',
        x: 60,
        z: -120,
        radius: 14,
        streetName: 'Jl. Pendidikan Timur',
        instructionText: 'Lurus terus ke timur melewati gedung Puskesmas Sehat.',
        subHint: 'Perhatikan trotoar cat blok hitam-putih.',
        completed: false,
        requiredRule: 'straight',
      },
      {
        id: 'm3-cp3',
        x: 180,
        z: -120,
        radius: 14,
        streetName: 'Pertigaan Jl. Diponegoro',
        instructionText: 'Di pertigaan Jl. Diponegoro, belok kanan ke arah selatan menuju Taman.',
        subHint: 'Belok ke arah selatan.',
        completed: false,
        requiredRule: 'turn_right',
      },
      {
        id: 'm3-cp4',
        x: 180,
        z: -65,
        radius: 14,
        streetName: 'Gerbang Taman Kota',
        instructionText: 'Masuki pelataran air mancur Taman Kota Ramah Anak.',
        subHint: 'Sentuh target kuning berkilau untuk menyelesaikan misi.',
        completed: false,
      },
    ],
  },
  {
    id: 4,
    title: 'Misi 4: Supermarket ke Kantor Balai Kota',
    locationFrom: 'Supermarket Nusantara (Titik A)',
    locationTo: 'Kantor Balai Kota Suka Maju (Titik B)',
    storyDescription:
      'Mengantarkan berkas penting warga dari Supermarket menuju Kantor Balai Kota! Rute melintasi boulevard utama Jl. Garuda Raya dan belok ke Jl. Merdeka Barat.',
    curriculumTopic: 'Kompetensi Navigasi Mandiri & Memori Rute',
    startPoint: { x: 40, z: -40, angle: Math.PI },
    targetPoint: { x: -140, z: -140, radius: 14, label: 'Pendopo Balai Kota' },
    targetTimeSeconds: 95,
    routeRoadNames: ['Jl. Garuda Raya', 'Jl. Merdeka Barat'],
    checkpoints: [
      {
        id: 'm4-cp1',
        x: 40,
        z: 0,
        radius: 14,
        streetName: 'Jl. Garuda Raya',
        instructionText: 'Masuki jalur Jl. Garuda Raya dan melajulah ke barat.',
        subHint: 'Patuhi batas kecepatan dan jalur marka aspal.',
        completed: false,
      },
      {
        id: 'm4-cp2',
        x: -20,
        z: 0,
        radius: 14,
        streetName: 'Perempatan Garuda & Pahlawan',
        instructionText: 'Lurus melintasi perempatan besar. Berhenti jika lampu APILL merah!',
        subHint: 'Pastikan lampu hijau sebelum melintasi perempatan.',
        completed: false,
        requiredRule: 'stop_line',
      },
      {
        id: 'm4-cp3',
        x: -140,
        z: 0,
        radius: 14,
        streetName: 'Pertigaan Jl. Merdeka Barat',
        instructionText: 'Di pertigaan Masjid Al-Ikhlas, belok kanan ke utara menyusuri Jl. Merdeka.',
        subHint: 'Patuhi rambu STOP sebelum berbelok.',
        completed: false,
        requiredRule: 'turn_right',
      },
      {
        id: 'm4-cp4',
        x: -140,
        z: -130,
        radius: 14,
        streetName: 'Halaman Balai Kota',
        instructionText: 'Tiba di Kantor Balai Kota Suka Maju. Parkir rapi di halaman utama.',
        subHint: 'Sentuh lingkaran target kuning.',
        completed: false,
      },
    ],
  },
  {
    id: 5,
    title: 'Misi 5: Stasiun Kereta Api ke Puskesmas Sehat',
    locationFrom: 'Stasiun Kereta Api Kota (Titik A)',
    locationTo: 'Puskesmas Sehat Bersama (Titik B)',
    storyDescription:
      'Menjemput petugas kesehatan yang baru tiba di Stasiun Kereta Api menuju Puskesmas Sehat! Rute melintasi perlintasan rel kereta api dan zebra cross ZOSS.',
    curriculumTopic: 'Perlintasan Rel Kereta Api & Layanan Kesehatan',
    startPoint: { x: -80, z: 45, angle: 0 },
    targetPoint: { x: 100, z: -140, radius: 14, label: 'Lobi Puskesmas Sehat' },
    targetTimeSeconds: 95,
    routeRoadNames: ['Jl. Pahlawan', 'Jl. Garuda Raya', 'Jl. Kartini Timur'],
    checkpoints: [
      {
        id: 'm5-cp1',
        x: -20,
        z: 45,
        radius: 14,
        streetName: 'Jl. Pahlawan',
        instructionText: 'Keluar dari area stasiun, belok kiri ke utara menyusuri Jl. Pahlawan.',
        subHint: 'Waspada perlintasan rel kereta api di sebelah selatan.',
        completed: false,
        requiredRule: 'turn_left',
      },
      {
        id: 'm5-cp2',
        x: -20,
        z: 0,
        radius: 14,
        streetName: 'Perempatan Garuda Raya',
        instructionText: 'Di perempatan Pos Polisi, belok kanan (timur) ke Jl. Garuda Raya.',
        subHint: 'Tunggu lampu hijau sebelum berbelok ke timur.',
        completed: false,
        requiredRule: 'turn_right',
      },
      {
        id: 'm5-cp3',
        x: 100,
        z: 0,
        radius: 14,
        streetName: 'Persimpangan Jl. Kartini',
        instructionText: 'Di persimpangan Jl. Kartini, belok kiri (utara) menuju Puskesmas.',
        subHint: 'Awas ada rambu Dilarang Belok Kanan, beloklah ke kiri!',
        completed: false,
        requiredRule: 'turn_left',
      },
      {
        id: 'm5-cp4',
        x: 100,
        z: -125,
        radius: 14,
        streetName: 'Halaman Puskesmas',
        instructionText: 'Tiba di Puskesmas Sehat Bersama! Masuki pelataran parkir.',
        subHint: 'Sentuh target berkilau untuk menuntaskan misi.',
        completed: false,
      },
    ],
  },
];
